using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using Windows.Foundation.Collections;
using ModelLibrary;
using Newtonsoft.Json;
using SikonConferenceSystem.Common;
using SikonConferenceSystem.Model;
using SikonConferenceSystem.Persistency;
using SikonConferenceSystem.ViewModel;
using SikonConferenceSystem.ViewModel.Interfaces;

namespace SikonConferenceSystem.Handler
{
    public class UserLoginCompositeHandler
    {
        private IUserLoginMenu _userLoginVm;
        private string _previousLoginId;

        public UserLoginCompositeHandler(IUserLoginMenu userLoginVm)
        {
            _userLoginVm = userLoginVm;
        }

        /*
        TODO: Reading(probably posting too) from the database with strings is not case sensitive, this is potentially very annoying. Can be fixed easily in terms of logging in, but could be major in terms of signing up.
        It means that a user with the email luckyluke@gmail.com could be unable to sign up if someone already has signed up with LuckyLuke@gmail.com as their mail.
        This is assumed related to the SQL statements generated by DBUtility, not the lib. itself but execution of the statements in SQL. 
        */
        public async void Login()
        {
            UserLoginMenuVM Vm = (UserLoginMenuVM)_userLoginVm;
            Vm.IsLoadingUser = true;
            Vm.WrongLogin = false;

            if (Vm.LoginId != _previousLoginId)
            {
                var consumer = CommonConsumerFactory.Create(new ConsumerStringIds<TupleJSON>());
                TupleJSON loginDetails =
                    await consumer.GetOneAsync(new[] { Vm.LoginId });


                if (loginDetails != null)
                    Vm.LoadedUser = GetUser(loginDetails);
            }

            if (Vm.Password == Vm.LoadedUser?.Password)
            {
                Vm.NavigationService?.Navigate((Type) Vm.NavigationService.UserLoginProfileMenu, Vm.LoadedUser);
            }
            else
            {
                Vm.WrongLogin = true;
            }

            _previousLoginId = Vm.LoginId;
            Vm.IsLoadingUser = false;
        }

        private User GetUser(TupleJSON loginDetails)
        {
            if (loginDetails.GetItem<User>(1) is User user)
            {
                return user;
            }
            if (loginDetails.GetItem<Speaker>(2) is Speaker speaker)
            {
                return speaker;
            }

            return loginDetails.GetItem<Admin>(3);
            
        }
    }
}
